version: "2.0"
services:
    nginx:
        image: nginx
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./default.conf:/etc/nginx/conf.d/default.conf
          - /etc/letsencrypt:/etc/letsencrypt

    db:
        image: postgres
        restart: always
        # ports:
        # -  "5432:5432"
        environment:
            POSTGRES_USER: "simple_user"
            POSTGRES_PASSWORD: simple_user
            POSTGRES_DB: "commentcloud"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        # volumes:
        #     - ./data:/var/lib/postgresql/pgdata

    comment-cloud:
        build:
            dockerfile: Dockerfile
            context: .
        restart: always
        command: python3 run.py
        volumes:
          - ./src:/usr/src

# volumes:
#     postgres_data:
